version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  test:
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tackle tests
          command: |
            pipenv run python manage.py test
